# Generated by Django 4.2.3 on 2023-07-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_lesson',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID намерения платежа Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID метода платежа Stripe'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stripe cтатус платежа'),
        ),
    ]
