# Generated by Django 4.2.3 on 2023-07-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_image', '0001_initial'),
        ('app_user', '0002_remove_payment_paid_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app_image.userimage', verbose_name='Аватар'),
        ),
    ]
