# Generated by Django 4.2.3 on 2023-07-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='courses/default.png', upload_to='courses/', verbose_name='Изображение курса')),
            ],
            options={
                'verbose_name': 'Изображение курса',
                'verbose_name_plural': 'Изображения курсов',
                'db_table': 'courses_images',
            },
        ),
        migrations.CreateModel(
            name='LessonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='lessons/default.png', upload_to='lessons/', verbose_name='Изображение урока')),
            ],
            options={
                'verbose_name': 'Изображение урока',
                'verbose_name_plural': 'Изображения уроков',
                'db_table': 'lesson_images',
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='users/default.png', upload_to='users/', verbose_name='Изображение пользователя')),
            ],
            options={
                'verbose_name': 'Изображение пользователя',
                'verbose_name_plural': 'Изображения пользователей',
                'db_table': 'user_images',
            },
        ),
    ]
